[package]
name = "bevy_asset_preview"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true, features = ["webp"] }
image = "0.25"
thiserror.workspace = true

[dev-dependencies]
tempfile = "3"
gltf = "1"
bytemuck = "1"
