[package]
name = "bevy_asset_preview"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true, features = ["webp"] }
image = { version = "0.25", features = ["webp"] }

[dev-dependencies]
tempfile = "3"
